export { default as User } from './User';
export type { IUser } from './User';
export { default as Student } from './Student';
export type { IStudent } from './Student';
export { default as Department } from './Department';
export type { IDepartment } from './Department';
export { default as Course } from './Course';
export type { ICourse } from './Course';
export { default as Attendance } from './Attendance';
export type { IAttendance } from './Attendance';
export { default as Announcement } from './Announcement';
export type { IAnnouncement } from './Announcement';
export { default as PasswordReset } from './PasswordReset';
export type { IPasswordReset } from './PasswordReset';
export { default as SystemLog } from './SystemLog';
export type { ISystemLog } from './SystemLog';
export { default as DTRTemplate } from './DTRTemplate';
export type { IDTRTemplate } from './DTRTemplate';
